new/tb_verilator_trace.sv
new/student_top.sv
new/Mem_IROM.sv
new/perip_bridge.sv
new/display_seg.sv
new/seg7.sv
new/dram_driver.sv
new/Mem_RAM.sv
new/counter.sv
imports/new/myCPU.sv
imports/new/defines.v
imports/new/open_risc_v.v
imports/new/pc_reg.v
imports/new/if_id.v
imports/new/id.v
imports/new/id_ex.v
imports/new/forwarding.v
imports/new/Hazard_detection_unit.v
imports/new/ex.v
imports/new/ctrl.v
imports/new/ex_mem1.v
imports/new/mem1.v
imports/new/mem1_mem2.v
imports/new/mem2.v
imports/new/mem2_wb.v
imports/new/wb.v
imports/new/reg.v
imports/new/dff_set.v
imports/new/branch_predictor.v
